name: Manual C++ Build

# Trigger manually from the Actions tab
on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest  # Windows runner

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Verify g++ is available
      - name: Check g++ version
        run: g++ --version

      # Step 3: Compile the C++ program
      - name: Compile main.cpp
        run: g++ main.cpp -o tester.exe -municode

      # Step 4: List output to confirm success
      - name: List output files
        run: dir
