name: Release Package

on:
  release:
    types: [ "created" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify g++ compiler
        run: g++ --version

      - name: Compile C++ code
        run: |
          g++ main.cpp -o tester.exe -municode
          dir

      - name: Prepare package folder
        run: |
          mkdir package
          copy tester.exe libfs\tester.exe

      - name: Create package zip
        run: |
          powershell -Command "Compress-Archive -Path libfs\\* -DestinationPath libfs.zip"

      - name: Publish to GitHub Packages
        uses: softprops/action-gh-release@v1
        with:
          name: libfs-v${{ github.run_number }}
          tag_name: libfs-v${{ github.run_number }}
          files: libfs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
