name: Release Package

on:
  push:
    tags:
      - 'libfs-v*'  # Triggers on tags like libfs-v1, libfs-v2, etc.
  workflow_dispatch:  # Also allows manual triggering

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify g++ compiler
        run: g++ --version

      - name: Compile C++ code
        run: |
          g++ main.cpp -o testrunner.exe -municode
          dir

      - name: Prepare package folder
        run: |
          mkdir package
          copy testrunner.exe package\testrunner.exe

      - name: Create package zip
        run: |
          powershell -Command "Compress-Archive -Path package\\* -DestinationPath testrunner.zip"

      - name: Publish to GitHub Packages
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: testrunner.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
